package hue.captains.singapura.js.homing.color.studio;

import hue.captains.singapura.js.homing.workspace.LifecycleHint;
import hue.captains.singapura.js.homing.workspace.WorkspaceWidget;

import java.util.List;

/**
 * The Color Studio's list pane — lists the colours within the group selected in
 * the {@link ColorTreeWidget}. A pure consumer of the {@code colornav} Party: it
 * fetches {@code /color-tree} once, then on each {@code NavigateTo} broadcast
 * walks to the selected node's tree path and renders that node's colour children
 * (name + meaning). Each re-render uses a fresh DomOpsParty sub-branch, dissolved
 * on the next (No DOM Destruction).
 *
 * <p>Each colour renders as a swatch + meaning + value ({@code /color-swatches}).
 * A <b>palette selector</b> at the top lets you inspect any registered theme's
 * concrete values without changing the page theme: picking a theme fetches
 * {@code /theme-vars?theme=<slug>} and resolves the structural/identity colours
 * (which map onto theme roles) to that theme's hexes. "Active theme (live)"
 * leaves them as {@code var(--…)} refs that follow the workspace chrome's theme.
 * Affective/symbolic colours are theme-independent anchors and don't vary.</p>
 */
public final class ColorListWidget extends WorkspaceWidget<WorkspaceWidget._None, ColorListWidget> {

    public static final ColorListWidget INSTANCE = new ColorListWidget();

    private ColorListWidget() {}

    private record construct() implements WorkspaceWidget._Construct<_None, ColorListWidget> {}

    @Override protected _Construct<_None, ColorListWidget> construct() { return new construct(); }
    @Override public Class<_None> paramsType() { return _None.class; }
    @Override public String title() { return "Colours"; }
    @Override public LifecycleHint lifecycleHint() { return LifecycleHint.MULTI; }

    @Override
    protected List<String> constructBodyJs() {
        return List.of(
                "    var root = branch.createElement('root', 'div');",
                "    root.style.cssText = 'height:100%;overflow:auto;box-sizing:border-box;'",
                "        + 'padding:12px 14px;font-family:system-ui,sans-serif;';",
                "",
                "    var __tree      = null;",
                "    var __pending   = null;",   // selection that arrived before the tree loaded
                "    var __swatches  = {};",     // name -> CSS colour (from /color-swatches)
                "    var __current   = null;",   // node currently rendered (re-render on swatch load)
                "    var __themeVars = null;",   // selected theme's --var -> hex map, or null (= live)
                "    var __themeLabel= null;",   // selected theme's display label
                "    var __owner     = Object.freeze({ toString: function () { return 'colorListWidget'; } });",
                "    var __renderBr  = null;",
                "    var __seq       = 0;",
                "",
                "    // ── Palette selector: inspect any theme's values (not the page theme) ──",
                "    var bar = branch.createElement('bar', 'div');",
                "    bar.style.cssText = 'display:flex;align-items:center;gap:8px;margin:0 0 12px;'",
                "        + 'padding-bottom:10px;border-bottom:1px solid rgba(0,0,0,.08);';",
                "    var barLabel = branch.createElement('barLabel', 'span');",
                "    barLabel.style.cssText = 'font-size:12px;color:#888;';",
                "    barLabel.textContent = 'Palette:';",
                "    var themeSel = branch.createElement('themeSel', 'select');",
                "    themeSel.style.cssText = 'font:inherit;font-size:13px;padding:3px 7px;'",
                "        + 'border:1px solid rgba(0,0,0,.2);border-radius:6px;background:#fff;cursor:pointer;';",
                "    var opt0 = branch.createElement('opt0', 'option');",
                "    opt0.value = ''; opt0.textContent = 'Active theme (live)';",
                "    themeSel.appendChild(opt0);",
                "    bar.appendChild(barLabel);",
                "    bar.appendChild(themeSel);",
                "    root.appendChild(bar);",
                "",
                "    var empty = branch.createElement('empty', 'div');",
                "    empty.style.cssText = 'color:#888;font-style:italic;line-height:1.5;padding:8px 2px;';",
                "    empty.textContent = 'Select a group in the Color Tree to list its colours.';",
                "    root.appendChild(empty);",
                "",
                "    function dimText(node, key) {",
                "        var ds = (node && node.dimensions) ? node.dimensions : [];",
                "        for (var i = 0; i < ds.length; i++) {",
                "            if (ds[i].key === key) return ds[i].text || '';",
                "        }",
                "        return '';",
                "    }",
                "    function nodeAt(rootNode, path) {",
                "        var n = rootNode;",
                "        var p = path || [];",
                "        for (var i = 0; i < p.length; i++) {",
                "            if (!n || !n.children || p[i] >= n.children.length) return null;",
                "            n = n.children[p[i]];",
                "        }",
                "        return n;",
                "    }",
                "",
                "    function tearDown() {",
                "        if (empty.parentNode) root.removeChild(empty);",
                "        if (__renderBr) { try { __renderBr.dissolve(); } catch (e) {} __renderBr = null; }",
                "    }",
                "    function showEmpty(msg) {",
                "        tearDown();",
                "        empty.textContent = msg || 'Select a group in the Color Tree to list its colours.';",
                "        root.appendChild(empty);",
                "    }",
                "",
                "    function render(node) {",
                "        __current = node;",
                "        if (!node) { showEmpty(); return; }",
                "        var colors = [];",
                "        if (dimText(node, 'kind') === 'color') {",
                "            colors = [node];",
                "        } else {",
                "            var kids = node.children || [];",
                "            for (var i = 0; i < kids.length; i++) {",
                "                if (dimText(kids[i], 'kind') === 'color') colors.push(kids[i]);",
                "            }",
                "        }",
                "        if (colors.length === 0) {",
                "            showEmpty('\\u201c' + (dimText(node, 'displayLabel') || 'This group')",
                "                + '\\u201d has no colours \\u2014 pick a leaf group "
                        + "(Affective, Symbolic, Identity, Structural).');",
                "            return;",
                "        }",
                "        tearDown();",
                "        var rb = branch.createBranch('list' + (++__seq));",
                "        rb.activate(__owner);",
                "        __renderBr = rb;",
                "        var host = rb.createElement('host', 'div');",
                "        root.appendChild(host);",
                "",
                "        var hdr = rb.createElement('hdr', 'div');",
                "        hdr.style.cssText = 'font-size:12px;text-transform:uppercase;letter-spacing:.06em;'",
                "            + 'color:#888;margin:2px 0 10px;';",
                "        hdr.textContent = (dimText(node, 'displayLabel') || 'Group') + ' \\u2014 '",
                "            + colors.length + ' colour' + (colors.length === 1 ? '' : 's')",
                "            + (__themeVars ? '  \\u00b7  ' + __themeLabel + ' palette' : '');",
                "        host.appendChild(hdr);",
                "",
                "        for (var j = 0; j < colors.length; j++) {",
                "            var c = colors[j];",
                "            var label = dimText(c, 'displayLabel');",
                "            var raw = __swatches[label] || 'transparent';",
                "            // With a theme selected, resolve var(--x) refs to THAT theme's hex.",
                "            var value = raw;",
                "            if (__themeVars && raw.indexOf('var(') === 0) {",
                "                var vn = raw.slice(4, raw.length - 1);",
                "                if (__themeVars[vn]) value = __themeVars[vn];",
                "            }",
                "            var row = rb.createElement('row' + j, 'div');",
                "            row.style.cssText = 'display:flex;align-items:flex-start;gap:12px;'",
                "                + 'border:1px solid rgba(0,0,0,.12);border-radius:8px;'",
                "                + 'padding:10px 12px;margin-bottom:8px;background:#fff;';",
                "            var sw = rb.createElement('sw' + j, 'div');",
                "            sw.style.cssText = 'flex:0 0 auto;width:34px;height:34px;border-radius:7px;'",
                "                + 'border:1px solid rgba(0,0,0,.18);box-shadow:inset 0 0 0 1px rgba(255,255,255,.35);'",
                "                + 'background:' + value + ';';",
                "            var col = rb.createElement('col' + j, 'div');",
                "            col.style.cssText = 'min-width:0;flex:1 1 auto;';",
                "            var name = rb.createElement('name' + j, 'div');",
                "            name.style.cssText = 'font-weight:600;font-size:15px;margin-bottom:2px;';",
                "            name.textContent = label;",
                "            var sum = rb.createElement('sum' + j, 'div');",
                "            sum.style.cssText = 'font-size:13px;color:#555;line-height:1.45;';",
                "            sum.textContent = dimText(c, 'summary');",
                "            var val = rb.createElement('val' + j, 'div');",
                "            val.style.cssText = 'font-family:ui-monospace,Menlo,Consolas,monospace;'",
                "                + 'font-size:11px;color:#8a94a6;margin-top:4px;';",
                "            val.textContent = value;",
                "            col.appendChild(name);",
                "            col.appendChild(sum);",
                "            col.appendChild(val);",
                "            row.appendChild(sw);",
                "            row.appendChild(col);",
                "            host.appendChild(row);",
                "        }",
                "    }",
                "",
                "    fetch('/color-tree')",
                "        .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })",
                "        .then(function (treeJson) {",
                "            __tree = treeJson;",
                "            if (__pending) { render(nodeAt(__tree, __pending.path)); __pending = null; }",
                "        })",
                "        .catch(function (err) {",
                "            showEmpty('Failed to load colours: ' + (err && err.message ? err.message : String(err)));",
                "        });",
                "",
                "    // Swatch table (name -> CSS colour). Loads independently; when it",
                "    // arrives, re-render whatever is showing so the chips fill in.",
                "    fetch('/color-swatches')",
                "        .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })",
                "        .then(function (sw) {",
                "            __swatches = sw || {};",
                "            if (__current) render(__current);",
                "        })",
                "        .catch(function (err) {",
                "            console.error('[ColorListWidget] swatch fetch failed:', err);",
                "        });",
                "",
                "    // Populate the palette selector with every registered theme.",
                "    fetch('/themes')",
                "        .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })",
                "        .then(function (data) {",
                "            var themes = (data && data.themes) ? data.themes : [];",
                "            for (var i = 0; i < themes.length; i++) {",
                "                var t = themes[i];",
                "                var o = branch.createElement('opt_' + t.slug, 'option');",
                "                o.value = t.slug; o.textContent = t.label || t.slug;",
                "                themeSel.appendChild(o);",
                "            }",
                "        })",
                "        .catch(function (err) {",
                "            console.error('[ColorListWidget] themes fetch failed:', err);",
                "        });",
                "",
                "    // Selecting a theme pins structural/identity swatches to that theme's",
                "    // actual values (fetched fresh); the empty value returns to live refs.",
                "    themeSel.onchange = function () {",
                "        var slug = themeSel.value;",
                "        __themeLabel = slug ? themeSel.options[themeSel.selectedIndex].textContent : null;",
                "        if (!slug) { __themeVars = null; if (__current) render(__current); return; }",
                "        fetch('/theme-vars?theme=' + encodeURIComponent(slug))",
                "            .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.text(); })",
                "            .then(function (css) {",
                "                var map = {}; var re = /(--[\\w-]+)\\s*:\\s*([^;]+);/g; var m;",
                "                while ((m = re.exec(css))) { map[m[1]] = m[2].replace(/^\\s+|\\s+$/g, ''); }",
                "                __themeVars = map;",
                "                if (__current) render(__current);",
                "            })",
                "            .catch(function (err) {",
                "                console.error('[ColorListWidget] theme-vars fetch failed:', err);",
                "            });",
                "    };",
                "",
                "    // ── colornav Party wiring ───────────────────────────────────",
                "    var __actorId    = null;",
                "    var __colorParty = (workspaceCtx && workspaceCtx.colorParty)",
                "                     ? workspaceCtx.colorParty : null;",
                "    if (__colorParty) {",
                "        __actorId = 'color/list-' + Math.random().toString(36).slice(2, 8);",
                "        __colorParty.joinActor({",
                "            id: __actorId,",
                "            parentSecretary: 'colornav',",
                "            reactors: {",
                "                NavigateTo: function (msg) {",
                "                    var sel = msg.node;",
                "                    if (!sel) return;",
                "                    if (!__tree) { __pending = sel; return; }",
                "                    render(nodeAt(__tree, sel.path));",
                "                }",
                "            }",
                "        });",
                "    }",
                "",
                "    return {",
                "        root: root,",
                "        setActive: function (active) {},",
                "        partyDeregister: function () {",
                "            tearDown();",
                "            if (__actorId && __colorParty) {",
                "                try { __colorParty.leave(__actorId); } catch (e) {}",
                "            }",
                "        }",
                "    };"
        );
    }
}
