/**
 * DomOpsParty.js
 *
 * Exports the page's party - the domOpsParty singleton - the party of
 * parties, and the level types: DomOpsParty, a party's root (depth 0), of two
 * kinds - StationedDomOpsParty, the page's one, and MobileDomOpsParty, any
 * other, made by the party of parties and grafted into the page's tree - and
 * DomOpsPartyL1 … DomOpsPartyL18 under either.
 *
 * Structure
 * ─────────
 *   domOpsParties                      ← the party of parties: the stationed one, and every mobile one
 *     .stationed                       ← domOpsParty
 *     .mobile(name)                → MobileDomOpsParty (depth 0 of its own), a stray until grafted
 *     .strays()                    → the mobile parties no one has grafted, as data
 *   domOpsParty                        ← the page's stationed party (depth 0)
 *     .createElement(name, tagName)    ← root-level element creation
 *     .createBranch(name)          → DomOpsPartyL1    (depth 1)
 *        .createBranch(name)       → DomOpsPartyL2    (depth 2)
 *           …
 *              .createBranch(name)  → DomOpsPartyL18  (depth 18, leaf)
 *
 * Each branch owns its elements directly and releases them on dissolve().
 * No component may call document.createElement() — all elements come from
 * branch.createElement(name, tagName).
 *
 * Classes are declared deepest-first (L18 → L17 → … → L1 → DomOpsParty) so
 * that each createBranch implementation references a class already in scope
 * at the point where the method body executes.
 *
 * Usage
 * ─────
 *   import { domOpsParty } from './src/party/DomOpsParty.js';
 *
 *   const branch  = domOpsParty.createBranch('nav');
 *   const navEl   = branch.createElement('nav', 'nav');
 *
 *   // Teardown — releases all owned elements and removes branch from party.
 *   branch.dissolve();
 *
 *   // A widget's own party, grafted by its host (RFC 0066 E3):
 *   const mine = domOpsParties.mobile('booksGrid-1');   // the widget's
 *   mine.activate(widget);
 *   hostBranch.graft('w-1', mine);                      // the host's: a proxy, fixed to it
 *   hostBranch.detach('w-1');                           // the proxy dissolved; a stray again
 */

// Framework-vendored. Original module-doc usage example:
//   import { domOpsParty } from 'homing-core-js/DomOpsPartyModule';
// The `import { _DomOpsPartyBase } from '...'` and `export { ... };` lines
// are generated by the framework's EsModuleWriter from the matching Java
// EsModule's ImportsFor / ExportsOf declarations — do not add them here.

// ── Level 18 — deepest level, no further branching ───────────────────────────
// createBranch is inherited from _DomOpsPartyBase and always throws RangeError.

class DomOpsPartyL18 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 18, deregister); }
}

// ── Level 17 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL17 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 17, deregister); }

  /** @param {string} name @returns {DomOpsPartyL18} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL18);
  }
}

// ── Level 16 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL16 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 16, deregister); }

  /** @param {string} name @returns {DomOpsPartyL17} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL17);
  }
}

// ── Level 15 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL15 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 15, deregister); }

  /** @param {string} name @returns {DomOpsPartyL16} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL16);
  }
}

// ── Level 14 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL14 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 14, deregister); }

  /** @param {string} name @returns {DomOpsPartyL15} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL15);
  }
}

// ── Level 13 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL13 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 13, deregister); }

  /** @param {string} name @returns {DomOpsPartyL14} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL14);
  }
}

// ── Level 12 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL12 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 12, deregister); }

  /** @param {string} name @returns {DomOpsPartyL13} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL13);
  }
}

// ── Level 11 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL11 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 11, deregister); }

  /** @param {string} name @returns {DomOpsPartyL12} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL12);
  }
}

// ── Level 10 ──────────────────────────────────────────────────────────────────

class DomOpsPartyL10 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 10, deregister); }

  /** @param {string} name @returns {DomOpsPartyL11} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL11);
  }
}

// ── Level 9 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL9 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 9, deregister); }

  /** @param {string} name @returns {DomOpsPartyL10} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL10);
  }
}

// ── Level 8 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL8 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 8, deregister); }

  /** @param {string} name @returns {DomOpsPartyL9} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL9);
  }
}

// ── Level 7 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL7 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 7, deregister); }

  /** @param {string} name @returns {DomOpsPartyL8} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL8);
  }
}

// ── Level 6 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL6 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 6, deregister); }

  /** @param {string} name @returns {DomOpsPartyL7} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL7);
  }
}

// ── Level 5 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL5 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 5, deregister); }

  /** @param {string} name @returns {DomOpsPartyL6} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL6);
  }
}

// ── Level 4 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL4 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 4, deregister); }

  /** @param {string} name @returns {DomOpsPartyL5} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL5);
  }
}

// ── Level 3 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL3 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 3, deregister); }

  /** @param {string} name @returns {DomOpsPartyL4} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL4);
  }
}

// ── Level 2 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL2 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 2, deregister); }

  /** @param {string} name @returns {DomOpsPartyL3} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL3);
  }
}

// ── Level 1 ───────────────────────────────────────────────────────────────────

class DomOpsPartyL1 extends _DomOpsPartyBase {
  /** @param {string} name @param {(() => void)|null} [deregister=null] */
  constructor(name, deregister) { super(name, 1, deregister); }

  /** @param {string} name @returns {DomOpsPartyL2} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL2);
  }
}

// ── Root (depth 0): Stationed or Mobile ───────────────────────────────────────

/**
 * A party's root (depth 0) — never itself, always one of its two kinds:
 * StationedDomOpsParty, the page's, or MobileDomOpsParty, any other. Under
 * either, the DomOpsPartyLN classes are created exclusively via createBranch(),
 * the levels counted from this root.
 */
class DomOpsParty extends _DomOpsPartyBase {
  /** @param {string} name @param {'stationed'|'mobile'} kind */
  constructor(name, kind) {
    if (new.target === DomOpsParty) {
      throw new TypeError("[DomOpsParty] a party is Stationed or Mobile: the page's is domOpsParty, and a mobile one comes from domOpsParties.mobile(name).");
    }
    super(name, 0, null, kind);
  }

  /** @param {string} name @returns {DomOpsPartyL1} */
  createBranch(name) {
    this._validateBranchName(name);
    return this._addBranch(name, DomOpsPartyL1);
  }
}

/** Whether the page has its stationed party: one per page, and no second. */
let _stationedMade = false;

/**
 * The page's party: the one stationed where the page is, the root of the
 * page's tree. Made once, as domOpsParty; every other party is mobile.
 */
class StationedDomOpsParty extends DomOpsParty {
  /** @param {string} [name='root'] */
  constructor(name = 'root') {
    if (_stationedMade) throw new Error("[DomOpsParty] the page has its stationed party already: domOpsParty.");
    super(name, 'stationed');
    _stationedMade = true;
  }
}

/** The party of parties' own mark: a mobile party is made by it, and by nothing else. */
const _MOBILE = Symbol('mobile');

/**
 * A party of its own — a widget's — made by the party of parties, working on
 * its own from the moment it is made, and grafted into the page's tree by a
 * host (branch.graft(name, party)). It takes its orders from above as a
 * branch does. Dissolved, it leaves the party of parties, and its proxy goes.
 */
class MobileDomOpsParty extends DomOpsParty {
  constructor(mark, name) {
    if (mark !== _MOBILE) throw new TypeError("[DomOpsParty] a mobile party comes from domOpsParties.mobile(name).");
    super(name, 'mobile');
  }

  dissolve() {
    super.dissolve();
    domOpsParties._left(this);
  }
}

/**
 * The party of parties: the page's stationed party, and every mobile party
 * made on the page — each made here, known here from the moment it is made
 * until it is dissolved, grafted or not. A mobile party no one has grafted is
 * a STRAY: said by strays(), where no snapshot of the page would see it.
 */
class DomOpsParties {
  /** @param {StationedDomOpsParty} stationed */
  constructor(stationed) {
    this._stationed = stationed;
    this._mobiles = new Map();   // name → a mobile party alive
  }

  /** The page's stationed party. @returns {StationedDomOpsParty} */
  get stationed() { return this._stationed; }

  /**
   * A mobile party, new: depth 0 of its own, a stray until a host grafts it.
   * Its name is its own, and no other mobile party alive has it.
   * @param {string} name @returns {MobileDomOpsParty}
   */
  mobile(name) {
    if (this._mobiles.has(name)) throw new RangeError(`[DomOpsParty] a mobile party named "${name}" is alive already.`);
    const party = new MobileDomOpsParty(_MOBILE, name);
    this._mobiles.set(name, party);
    return party;
  }

  /** Every mobile party alive, grafted or not. @returns {MobileDomOpsParty[]} */
  mobiles() { return [...this._mobiles.values()]; }

  /** The mobile parties no one has grafted, as data. */
  strays() { return Object.freeze(this.mobiles().filter(m => !m.isGrafted).map(m => m.snapshot())); }

  /** The page's tree — every grafted party read through its proxy — and the strays beside it, as data. */
  snapshot() { return Object.freeze({ stationed: this._stationed.snapshot(), strays: this.strays() }); }

  /** A mobile party dissolved leaves. */
  _left(party) { if (this._mobiles.get(party.name) === party) this._mobiles.delete(party.name); }
}

// ─── Global singletons ───────────────────────────────────────────────────────
const domOpsParty = new StationedDomOpsParty('root');

// The root owns itself. There is nothing above it and it cannot dissolve, so
// "owned by the party" is the truth rather than a sentinel standing in for it —
// and the singleton is retained by this module for as long as the page lives,
// which is what makes the owner reachable. RFC 0063 found the previous form
// wrong: a module-level const that is neither exported nor captured is not
// retained by V8, and the root read as leaked on every workspace.
domOpsParty.activate(domOpsParty, 'partyChief');

/** The page's party of parties: its stationed party, and every mobile party made on the page. */
const domOpsParties = new DomOpsParties(domOpsParty);

// ─── View ────────────────────────────────────────────────────────────────────

/**
 * The party tree as data — RFC 0063's observation by construction.
 *
 * This is the ONLY thing a monitor imports. Not `domOpsParty`: that is the
 * root handle, and a widget inside the tree it renders must not hold the
 * handle that could dissolve its own host. What comes back is a deep-frozen
 * snapshot with no function and no live reference in it.
 *
 * @returns {ReturnType<_DomOpsPartyBase['snapshot']>}
 */
const viewParty = () => domOpsParty.snapshot();
