package hue.captains.singapura.js.homing.codec.java;

import hue.captains.singapura.js.homing.codec.FunctionsCodeGen;
import hue.captains.singapura.js.homing.codec.ObjectDefinition;
import hue.captains.singapura.tao.ontology.StatelessFunctionalObject;

import java.lang.reflect.ParameterizedType;
import java.lang.reflect.RecordComponent;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

/**
 * Concrete {@link FunctionsCodeGen} that emits a <b>Java</b> JSON codec — a
 * {@code TransformationFunctions<T, String>} implementation — for a record
 * {@link ObjectDefinition}. The Java counterpart of {@code EcmaFunctionsCodeGen}:
 * same ontology, host-language target.
 *
 * <p>No {@code DefinitionCodeGen} companion is needed — in Java the record IS the
 * type declaration. The emitted codec builds/reads a Vert.x {@code JsonObject}
 * (so escaping and parsing are the JSON library's job) and constructs the record
 * via its canonical constructor. Types are fully qualified in the emitted source,
 * so the generator manages no imports and the output drops into any package.</p>
 *
 * <p>Supported component shapes (the report model's needs): {@code String}, the
 * primitive scalars ({@code int/long/boolean/double} + boxed), enums (wire =
 * constant name), nested records (delegate to {@code <Name>Codec}), and {@code
 * List<String>} / {@code List<enum>} / {@code List<record>}. Anything else fails
 * loud at generation time. Nested-record codecs are referenced by simple name —
 * every record in one manifest generates into the same package.</p>
 *
 * <p>Stateless Functional Object; {@link #INSTANCE} is the canonical handle.</p>
 */
public record JavaFunctionsCodeGen() implements FunctionsCodeGen, StatelessFunctionalObject {

    public static final JavaFunctionsCodeGen INSTANCE = new JavaFunctionsCodeGen();

    /** The package the generated codecs are emitted into (referenced for nested-codec lookup). */
    public static final String CODEC_PACKAGE = "hue.captains.singapura.js.homing.conformance.report.codec";

    private static final String JSON_OBJECT = "io.vertx.core.json.JsonObject";
    private static final String JSON_ARRAY  = "io.vertx.core.json.JsonArray";

    @Override
    public String generate(ObjectDefinition<?> definition) {
        Class<?> type = definition.type();
        if (!type.isRecord()) {
            throw new IllegalArgumentException("JavaFunctionsCodeGen supports record types only — got " + type);
        }
        return generateRecord(type);
    }

    private String generateRecord(Class<?> type) {
        String fqn      = type.getCanonicalName();
        String codec    = type.getSimpleName() + "Codec";
        RecordComponent[] cs = type.getRecordComponents();

        var sb = new StringBuilder();
        sb.append("package ").append(CODEC_PACKAGE).append(";\n\n");
        sb.append("/** Generated by JavaFunctionsCodeGen — do not edit. Codec for ").append(fqn).append(". */\n");
        sb.append("public final class ").append(codec)
          .append(" implements hue.captains.singapura.js.homing.codec.TransformationFunctions<")
          .append(fqn).append(", String> {\n\n");
        sb.append("    public static final ").append(codec).append(" INSTANCE = new ").append(codec).append("();\n\n");

        // ---- toJson ----
        sb.append("    public static ").append(JSON_OBJECT).append(" toJson(").append(fqn).append(" t) {\n");
        sb.append("        ").append(JSON_OBJECT).append(" o = new ").append(JSON_OBJECT).append("();\n");
        for (RecordComponent c : cs) emitToJson(sb, c);
        sb.append("        return o;\n");
        sb.append("    }\n\n");

        // ---- fromJson ----
        sb.append("    public static ").append(fqn).append(" fromJson(").append(JSON_OBJECT).append(" o) {\n");
        var args = new ArrayList<String>();
        for (RecordComponent c : cs) args.add(emitFromJson(sb, c));
        sb.append("        return new ").append(fqn).append("(").append(String.join(", ", args)).append(");\n");
        sb.append("    }\n\n");

        // ---- TransformationFunctions ----
        sb.append("    @Override public String transformTo(").append(fqn).append(" t) { return toJson(t).encode(); }\n");
        sb.append("    @Override public ").append(fqn).append(" transformFrom(String wire) { return fromJson(new ")
          .append(JSON_OBJECT).append("(wire)); }\n");
        sb.append("}\n");
        return sb.toString();
    }

    private void emitToJson(StringBuilder sb, RecordComponent c) {
        String n = c.getName();
        String get = "t." + n + "()";
        switch (kind(c)) {
            case STRING, INT, LONG, BOOLEAN, DOUBLE ->
                    sb.append("        o.put(\"").append(n).append("\", ").append(get).append(");\n");
            case ENUM ->
                    sb.append("        o.put(\"").append(n).append("\", ").append(get).append(".name());\n");
            case RECORD ->
                    sb.append("        o.put(\"").append(n).append("\", ").append(codecOf(c.getType()))
                      .append(".toJson(").append(get).append("));\n");
            case LIST_STRING -> {
                sb.append("        ").append(JSON_ARRAY).append(" _").append(n).append(" = new ").append(JSON_ARRAY).append("();\n");
                sb.append("        for (String e : ").append(get).append(") _").append(n).append(".add(e);\n");
                sb.append("        o.put(\"").append(n).append("\", _").append(n).append(");\n");
            }
            case LIST_ENUM -> {
                sb.append("        ").append(JSON_ARRAY).append(" _").append(n).append(" = new ").append(JSON_ARRAY).append("();\n");
                sb.append("        for (").append(listElem(c).getCanonicalName()).append(" e : ").append(get)
                  .append(") _").append(n).append(".add(e.name());\n");
                sb.append("        o.put(\"").append(n).append("\", _").append(n).append(");\n");
            }
            case LIST_RECORD -> {
                sb.append("        ").append(JSON_ARRAY).append(" _").append(n).append(" = new ").append(JSON_ARRAY).append("();\n");
                sb.append("        for (").append(listElem(c).getCanonicalName()).append(" e : ").append(get)
                  .append(") _").append(n).append(".add(").append(codecOf(listElem(c))).append(".toJson(e));\n");
                sb.append("        o.put(\"").append(n).append("\", _").append(n).append(");\n");
            }
        }
    }

    /** Emits any needed decode statements and returns the constructor-argument expression for this component. */
    private String emitFromJson(StringBuilder sb, RecordComponent c) {
        String n = c.getName();
        String key = "\"" + n + "\"";
        return switch (kind(c)) {
            case STRING  -> "o.getString("  + key + ")";
            case INT     -> "o.getInteger(" + key + ")";
            case LONG    -> "o.getLong("    + key + ")";
            case BOOLEAN -> "o.getBoolean(" + key + ")";
            case DOUBLE  -> "o.getDouble("  + key + ")";
            case ENUM    -> c.getType().getCanonicalName() + ".valueOf(o.getString(" + key + "))";
            case RECORD  -> codecOf(c.getType()) + ".fromJson(o.getJsonObject(" + key + "))";
            case LIST_STRING -> emitListDecode(sb, n, key, "String", "a.getString(i)");
            case LIST_ENUM   -> emitListDecode(sb, n, key, listElem(c).getCanonicalName(),
                    listElem(c).getCanonicalName() + ".valueOf(a.getString(i))");
            case LIST_RECORD -> emitListDecode(sb, n, key, listElem(c).getCanonicalName(),
                    codecOf(listElem(c)) + ".fromJson(a.getJsonObject(i))");
        };
    }

    private String emitListDecode(StringBuilder sb, String n, String key, String elemType, String elemExpr) {
        String local = "_" + n;
        sb.append("        java.util.List<").append(elemType).append("> ").append(local)
          .append(" = new java.util.ArrayList<>();\n");
        sb.append("        { ").append(JSON_ARRAY).append(" a = o.getJsonArray(").append(key).append(");\n");
        sb.append("          for (int i = 0; i < a.size(); i++) ").append(local).append(".add(").append(elemExpr).append("); }\n");
        return "java.util.List.copyOf(" + local + ")";
    }

    private enum Kind { STRING, INT, LONG, BOOLEAN, DOUBLE, ENUM, RECORD, LIST_STRING, LIST_ENUM, LIST_RECORD }

    private static Kind kind(RecordComponent c) {
        Class<?> raw = c.getType();
        if (raw == String.class)  return Kind.STRING;
        if (raw == int.class     || raw == Integer.class) return Kind.INT;
        if (raw == long.class    || raw == Long.class)    return Kind.LONG;
        if (raw == boolean.class || raw == Boolean.class) return Kind.BOOLEAN;
        if (raw == double.class  || raw == Double.class)  return Kind.DOUBLE;
        if (raw.isEnum())   return Kind.ENUM;
        if (raw.isRecord()) return Kind.RECORD;
        if (List.class.isAssignableFrom(raw)) {
            Class<?> elem = listElem(c);
            if (elem == String.class) return Kind.LIST_STRING;
            if (elem.isEnum())        return Kind.LIST_ENUM;
            if (elem.isRecord())      return Kind.LIST_RECORD;
            throw new IllegalArgumentException("Unsupported List element " + elem + " on " + c);
        }
        throw new IllegalArgumentException("Unsupported record component " + raw + " on " + c);
    }

    private static Class<?> listElem(RecordComponent c) {
        Type g = c.getGenericType();
        if (g instanceof ParameterizedType p && p.getActualTypeArguments()[0] instanceof Class<?> k) return k;
        throw new IllegalArgumentException("List component must have a concrete element type: " + c);
    }

    /** The simple-name codec class for a nested record type (same generated package). */
    private static String codecOf(Class<?> recordType) {
        return recordType.getSimpleName() + "Codec";
    }
}
