package hue.captains.singapura.js.homing.conformance.studio;

import hue.captains.singapura.js.homing.codec.ObjectDefinition;
import hue.captains.singapura.js.homing.codec.ecma.EcmaDefinitionCodeGen;
import hue.captains.singapura.js.homing.codec.ecma.EcmaFunctionsCodeGen;
import hue.captains.singapura.js.homing.conformance.report.gen.ReportCodecManifest;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * RFC 0044 Phase 8 — the polyglot codec's <b>JS target</b>: applies the ECMA
 * generators to the same {@link ReportCodecManifest} the Java target uses,
 * emitting one ES-module body ({@code ReportCodecsModule.js}) with, per report
 * record, a JS class declaration + its codec. Served by {@link ReportCodecsModule}
 * so the studio widgets decode the exported report client-side into typed
 * instances — the same schema, generated to both languages.
 *
 * <p>Build-time only (data, not source): invoked by the {@code exec} plugin at
 * process-classes, written into {@code target/classes/homing/js/...} where the
 * framework serves it as a normal module resource. Never committed.</p>
 */
public final class ReportJsCodecGen {

    private ReportJsCodecGen() {}

    /** The served module's file name — must match {@link ReportCodecsModule}'s simple name. */
    public static final String OUTPUT_FILE = "ReportCodecsModule.js";

    public static void main(String[] args) throws IOException {
        if (args.length != 1) {
            throw new IllegalArgumentException("Usage: ReportJsCodecGen <output-directory>");
        }
        Path outDir = Paths.get(args[0]);
        Files.createDirectories(outDir);
        Files.writeString(outDir.resolve(OUTPUT_FILE), generate(), StandardCharsets.UTF_8);
        System.out.println("[ReportJsCodecGen] wrote " + OUTPUT_FILE
                + " (" + ReportCodecManifest.ENTRIES.size() + " entries)");
    }

    /** The full ES-module body: each report record's JS class + codec, concatenated. */
    public static String generate() {
        var sb = new StringBuilder();
        sb.append("// Generated by ReportJsCodecGen — do not edit by hand.\n");
        sb.append("// Source-of-truth: ReportCodecManifest (the report record ObjectDefinitions).\n\n");
        for (ObjectDefinition<?> def : ReportCodecManifest.ENTRIES) {
            sb.append(EcmaDefinitionCodeGen.INSTANCE.generate(def)).append('\n');
            sb.append(EcmaFunctionsCodeGen.INSTANCE.generate(def)).append('\n');
        }
        return sb.toString();
    }
}
